services:
  postgres:
    image: docker.io/postgres:15
    volumes:
      - ./:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: passwordpusher_user
      POSTGRES_PASSWORD: passwordpusher_passwd
      POSTGRES_DB: passwordpusher_db

  pwpush:
    image: docker.io/pglombardo/pwpush:latest
    environment:
      DATABASE_URL: 'postgres://passwordpusher_user:passwordpusher_passwd@postgres:5432/passwordpusher_db'
    ports:
      - "5100:5100"
    restart: unless-stopped
    depends_on:
      - postgres
    links:
     - postgres:postgres
